// <auto-generated />
using System;
using System.Net;
using LokynexHealth.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LokynexHealth.Infrastructure.Migrations.SyncDocsSchema
{
    [DbContext(typeof(LokynexHealthDbContext))]
    [Migration("20260706123315_sync_docs_schema")]
    partial class sync_docs_schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hms")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LokynexHealth.Domain.Entities.AiInteractionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiSuggestion")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_suggestion");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("feature_name");

                    b.Property<string>("InputPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_payload");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module_name");

                    b.Property<string>("OverrideReason")
                        .HasColumnType("text")
                        .HasColumnName("override_reason");

                    b.Property<bool>("PhiSentExternally")
                        .HasColumnType("boolean")
                        .HasColumnName("phi_sent_externally");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_status");

                    b.Property<Guid?>("ReviewedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_staff_id");

                    b.Property<Guid?>("SourceRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceRecordTable")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_table");

                    b.HasKey("Id");

                    b.HasIndex("ModuleName", "FeatureName");

                    b.HasIndex("SourceRecordTable", "SourceRecordId");

                    b.ToTable("ai_interaction_log", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.BillingClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("approved_amount");

                    b.Property<string>("ClaimNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("claim_number");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<decimal>("ClaimedAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("claimed_amount");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid?>("PatientInsuranceId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_insurance_id");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PatientInsuranceId");

                    b.ToTable("billing_claims", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.BillingInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("admission_id");

                    b.Property<decimal>("CgstAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cgst_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount_amount");

                    b.Property<string>("EwayBillNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("eway_bill_number");

                    b.Property<decimal>("IgstAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("igst_amount");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("invoice_number");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_status");

                    b.Property<decimal>("SgstAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("sgst_amount");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.ToTable("billing_invoices", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.BillingInvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("GstRatePct")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("gst_rate_pct");

                    b.Property<string>("HsnSacCode")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("hsn_sac_code");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("line_total");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("quantity");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_module");

                    b.Property<Guid?>("SourceRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_record_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("billing_invoice_items", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.BillingPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_number");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("billing_payments", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.BillingRateMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("PackageCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("package_code");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("rate");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scheme_name");

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("text")
                        .HasColumnName("service_description");

                    b.HasKey("Id");

                    b.ToTable("billing_rate_masters", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.BillingRoomCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("admission_id");

                    b.Property<Guid>("BedId")
                        .HasColumnType("uuid")
                        .HasColumnName("bed_id");

                    b.Property<DateTimeOffset>("ChargeFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("charge_from");

                    b.Property<DateTimeOffset>("ChargeTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("charge_to");

                    b.Property<decimal>("ComputedAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("computed_amount");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("daily_rate");

                    b.Property<Guid?>("InvoiceItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_item_id");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceItemId");

                    b.ToTable("billing_room_charges", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AadhaarPkiCertRef")
                        .HasColumnType("text")
                        .HasColumnName("aadhaar_pki_cert_ref");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NmcRegistrationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nmc_registration_no");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialization");

                    b.HasKey("Id");

                    b.HasIndex("NmcRegistrationNo")
                        .IsUnique();

                    b.ToTable("doctors", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.OpdDiagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AiLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_log_id");

                    b.Property<bool>("AiSuggested")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_suggested");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Icd10Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("icd10_code");

                    b.Property<string>("Icd10Description")
                        .HasColumnType("text")
                        .HasColumnName("icd10_description");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id");

                    b.HasIndex("AiLogId");

                    b.HasIndex("VisitId");

                    b.ToTable("opd_diagnoses", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.OpdInvestigationOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("FulfilledReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("fulfilled_reference_id");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("order_type");

                    b.Property<DateTimeOffset>("OrderedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ordered_at");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("TestOrStudyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("test_or_study_name");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id");

                    b.HasIndex("VisitId");

                    b.ToTable("opd_investigation_orders", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.OpdSoapNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AiDrafted")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_drafted");

                    b.Property<Guid?>("AiLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_log_id");

                    b.Property<string>("Assessment")
                        .HasColumnType("text")
                        .HasColumnName("assessment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("FinalizedByDoctor")
                        .HasColumnType("boolean")
                        .HasColumnName("finalized_by_doctor");

                    b.Property<string>("Objective")
                        .HasColumnType("text")
                        .HasColumnName("objective");

                    b.Property<string>("Plan")
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("source_language");

                    b.Property<string>("Subjective")
                        .HasColumnType("text")
                        .HasColumnName("subjective");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id");

                    b.HasIndex("AiLogId");

                    b.HasIndex("VisitId");

                    b.ToTable("opd_soap_notes", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.OpdTokenQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("called_at");

                    b.Property<DateTimeOffset>("CheckedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_in_at");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateOnly>("QueueDate")
                        .HasColumnType("date")
                        .HasColumnName("queue_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TokenNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("token_number");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("QueueDate", "DoctorId");

                    b.HasIndex("DoctorId", "QueueDate", "TokenNumber")
                        .IsUnique();

                    b.ToTable("opd_token_queue", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.OpdVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChiefComplaint")
                        .HasColumnType("text")
                        .HasColumnName("chief_complaint");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<string>("EsignQrCodeRef")
                        .HasColumnType("text")
                        .HasColumnName("esign_qr_code_ref");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("SchemeTag")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scheme_tag");

                    b.Property<bool>("SignedOff")
                        .HasColumnType("boolean")
                        .HasColumnName("signed_off");

                    b.Property<DateTimeOffset?>("SignedOffAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_off_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<DateTimeOffset?>("VisitEndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visit_ended_at");

                    b.Property<string>("VisitNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("visit_number");

                    b.Property<DateTimeOffset>("VisitStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visit_started_at");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("TokenId");

                    b.HasIndex("VisitNumber")
                        .IsUnique();

                    b.HasIndex("DoctorId", "VisitStartedAt");

                    b.ToTable("opd_visits", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AadhaarLast4")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("aadhaar_last4");

                    b.Property<byte[]>("AadhaarNumberEnc")
                        .HasColumnType("bytea")
                        .HasColumnName("aadhaar_number_enc");

                    b.Property<string>("AbhaId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("abha_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AltMobile")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("alt_mobile");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("blood_group");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<Guid?>("IsDuplicateOf")
                        .HasColumnType("uuid")
                        .HasColumnName("is_duplicate_of");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("mobile");

                    b.Property<string>("PanNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pan_number");

                    b.Property<string>("PinCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("pin_code");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("preferred_language");

                    b.Property<Guid?>("RegisteredAtTenantBranch")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_at_tenant_branch");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Uhid")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("uhid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AbhaId");

                    b.HasIndex("Mobile");

                    b.HasIndex("Uhid")
                        .IsUnique();

                    b.ToTable("patients", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.PatientConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CapturedVia")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("captured_via");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("consent_type");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "ConsentType");

                    b.ToTable("patient_consents", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.PatientDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<decimal?>("OcrConfidence")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("ocr_confidence");

                    b.Property<string>("OcrExtractedJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ocr_extracted_json");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("patient_documents", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.PatientInsurance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EligibilityCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eligibility_checked_at");

                    b.Property<bool>("EligibilityVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("eligibility_verified");

                    b.Property<string>("InsuranceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("insurance_type");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("SchemeNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scheme_number");

                    b.Property<string>("TpaName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("tpa_name");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("patient_insurance", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PrescriptionNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("prescription_number");

                    b.Property<bool>("PushedToAbha")
                        .HasColumnType("boolean")
                        .HasColumnName("pushed_to_abha");

                    b.Property<bool>("PushedToPharmacyQueue")
                        .HasColumnType("boolean")
                        .HasColumnName("pushed_to_pharmacy_queue");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PrescriptionNumber")
                        .IsUnique();

                    b.HasIndex("VisitId");

                    b.ToTable("prescriptions", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.PrescriptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AiAutocompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_autocompleted");

                    b.Property<Guid?>("AiLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_log_id");

                    b.Property<string>("AllergyWarning")
                        .HasColumnType("text")
                        .HasColumnName("allergy_warning");

                    b.Property<string>("Dosage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dosage");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("drug_name");

                    b.Property<short?>("DurationDays")
                        .HasColumnType("smallint")
                        .HasColumnName("duration_days");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("frequency");

                    b.Property<bool>("InteractionChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("interaction_checked");

                    b.Property<string>("InteractionWarning")
                        .HasColumnType("text")
                        .HasColumnName("interaction_warning");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prescription_id");

                    b.Property<string>("RxnormCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rxnorm_code");

                    b.Property<string>("ScheduleFlag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schedule_flag");

                    b.HasKey("Id");

                    b.HasIndex("AiLogId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("prescription_items", "hms");
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.BillingClaim", b =>
                {
                    b.HasOne("LokynexHealth.Domain.Entities.BillingInvoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LokynexHealth.Domain.Entities.PatientInsurance", null)
                        .WithMany()
                        .HasForeignKey("PatientInsuranceId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.BillingInvoice", b =>
                {
                    b.HasOne("LokynexHealth.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.BillingInvoiceItem", b =>
                {
                    b.HasOne("LokynexHealth.Domain.Entities.BillingInvoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.BillingPayment", b =>
                {
                    b.HasOne("LokynexHealth.Domain.Entities.BillingInvoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.BillingRoomCharge", b =>
                {
                    b.HasOne("LokynexHealth.Domain.Entities.BillingInvoiceItem", null)
                        .WithMany()
                        .HasForeignKey("InvoiceItemId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.OpdDiagnosis", b =>
                {
                    b.HasOne("LokynexHealth.Domain.Entities.AiInteractionLog", null)
                        .WithMany()
                        .HasForeignKey("AiLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LokynexHealth.Domain.Entities.OpdVisit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.OpdInvestigationOrder", b =>
                {
                    b.HasOne("LokynexHealth.Domain.Entities.OpdVisit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.OpdSoapNote", b =>
                {
                    b.HasOne("LokynexHealth.Domain.Entities.AiInteractionLog", null)
                        .WithMany()
                        .HasForeignKey("AiLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LokynexHealth.Domain.Entities.OpdVisit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.OpdTokenQueue", b =>
                {
                    b.HasOne("LokynexHealth.Domain.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LokynexHealth.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.OpdVisit", b =>
                {
                    b.HasOne("LokynexHealth.Domain.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LokynexHealth.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LokynexHealth.Domain.Entities.OpdTokenQueue", null)
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.PatientConsent", b =>
                {
                    b.HasOne("LokynexHealth.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.PatientDocument", b =>
                {
                    b.HasOne("LokynexHealth.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.PatientInsurance", b =>
                {
                    b.HasOne("LokynexHealth.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("LokynexHealth.Domain.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LokynexHealth.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LokynexHealth.Domain.Entities.OpdVisit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LokynexHealth.Domain.Entities.PrescriptionItem", b =>
                {
                    b.HasOne("LokynexHealth.Domain.Entities.AiInteractionLog", null)
                        .WithMany()
                        .HasForeignKey("AiLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LokynexHealth.Domain.Entities.Prescription", null)
                        .WithMany()
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
